lang: en_message.yml

customdropmobs:
  ZOMBIE:
    drops:
      "5":  # 5% chance
        ROTTEN_FLESH: 5
      "1":  # 1% chance
        DIAMOND: 1
      "10":  # 10% chance
        COMMAND: "say %player% killed a zombie!"
  SKELETON:
    drops:
      "100":  # 100% chance, no randomization
        BONE: 3
        ARROW: 5