name: CustomDropMobs
version: '1.0'
main: me.phantam.customdropmobs.CustomDropMobs
api-version: '1.13'

commands:
  customdropmobs:
    aliases: [cdm]
    description: "View plugin commands"
    usage: "/cdm <reload | add | remove | list | toggle | clean>"
    permission: customdropmobs.admin

  reload:
    description: "Reload all configuration and messages"
    usage: "/cdm reload"
    permission: customdropmobs.reload

  toggle:
    description: "Toggle the plugin's functionality"
    usage: "/cdm toggle"
    permission: customdropmobs.toggle

  add:
    description: "Add a custom drop to a mob"
    usage: "/cdm add <mob> <item> [chance]"
    permission: customdropmobs.modify

  remove:
    description: "Remove a custom drop from a mob"
    usage: "/cdm remove <mob> <item>"
    permission: customdropmobs.modify

  list:
    description: "List all custom drops"
    usage: "/cdm list [mob]"
    permission: customdropmobs.view

  menu:
    description: "Open the CustomDropMobs menu"
    usage: "/cdm menu"
    permission: customdropmobs.menu

permissions:
  customdropmobs.admin:
    description: "Allows use of /cdm command"
    default: op

  customdropmobs.reload:
    description: "Allows use of /cdm reload"
    default: op

  customdropmobs.toggle:
    description: "Allows use of /cdm toggle"
    default: op

  customdropmobs.add:
    description: "Allows use of /cdm add"
    default: op

  customdropmobs.remove:
    description: "Allows use of /cdm remove"
    default: op

  customdropmobs.menu:
    description: "Allows use of /cdm menu"
    default: op